### PR TITLE
feat(l10n): Added Telugu (te) language support

### PR DESCRIPTION
**Pull request by SpaciousCoder78**
## Pull request checklist

- [x] Lint and unit tests pass locally with my changes
- [ ] Extended the README / documentation, if necessary

## Pull request type

Type: Translation

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

(Write your answer here.)

## Other information

Added Telugu Language support to the app

### CODE REVIEW

**Comment by kamilprusko** [comment]
Hi @SpaciousCoder78 

Translations looks great until line 543. You have missed a few messages for stats and utils (notifications)... and `translator-credits` is for your name if you want to appear in the about dialog.

**Comment by SpaciousCoder78** [comment]
Will look into it and fix it

**Comment by SpaciousCoder78** [comment]
@kamilprusko I fixed the translation as you suggested. Please check my commit again.

**Comment by kamilprusko** [comment]
Looks great! Thanks!

**Pull request merged**
