### PR TITLE
Add 'skip' button to main window, and preference to show it

### PR DESCRIPTION
**Pull request by jimduchek**
## Pull request checklist

- [*] Lint and unit tests pass locally with my changes
- [N/A] Extended the README / documentation, if necessary

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [*] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

There is no 'skip' button in the main window.

Issue Number: N/A

## What is the new behavior?

Now there is a 'skip' button.

### CODE REVIEW

**Comment by kamilprusko** [comment]
Hi @jimduchek 

Thank you for contributing!

Agree, the skip button should be there. In wip/gtk4 branch it's already added:

[Screencast from 2023-01-28 15-31-02.webm](https://user-images.githubusercontent.com/1135423/215272163-ea52eefa-9079-4e36-a59f-545b54ee0b92.webm)

Regarding your proposal:
1. In my opinion the primary button (Start / Pause / Resume) should be in the center.
2. Ideally, it shouldn't be optional.
3. The "Next" hint: I'd prefer "Take a break" / "Start Pomodoro".

Regarding my proposal:
1. The skip button comes with a sacrifice of stop button... It shows up after pausing the timer... which may be controversial.
2. The left button is for rewinding the timer. In stats / history it will be treated as interruptions, like pause/resume, but afterwards.

I also would like to have same button layout in the app and the indicator menu in GNOME Shell, mockup:
rect13565

@jimduchek  What do you think?

_Disclaimer: wip/gtk4 branch is not usable at the moment_

**Comment by jimduchek** [comment]
> 1. In my opinion the primary button (Start / Pause / Resume) should be in the center.

Agreed, I didn't even consider that, I just tacked Skip on the end.  
> 2. Ideally, it shouldn't be optional.

Personally?  I always want it there.  But there are #601 type people who I think may consider a skip button to be unwelcome. Ideally I think there'd be a proper 'strict mode' as opposed to simply individual control of this button being visible or not, but I'm not going be the one to implement that.
> 3. The "Next" hint: I'd prefer "Take a break" / "Start Pomodoro".

I like.  The pause/resume button should switch too... 
> 
> Regarding my proposal:
> 
> 1. The skip button comes with a sacrifice of stop button... It shows up after pausing the timer... which may be controversial.
> 2. The left button is for rewinding the timer. In stats / history it will be treated as interruptions, like pause/resume, but afterwards.

I like both of those, I think.  That's the way in the gtk4/wip version?
> 
> I also would like to have same button layout in the app and the indicator menu in GNOME Shell, mockup: rect13565

I don't use GNOME, so I've not seen any of the GNOME shell/extension stuff.  This is the only pomodoro app that allows running of arbitrary commands on state changes, though... :)
> 
> _Disclaimer: wip/gtk4 branch is not usable at the moment_

How unusable is it?  May see if I can get it to build.

Pushing a new commit based on the above.  May be a bit overkill (changing the button order depending on whether or not "Skip" is shown for example... but I hate to change an interface people are used to).

**Comment by kamilprusko** [comment]
I'll get back to it next week. I'd like to adjust the buttons in the GNOME Shell indicator accordingly.

> How unusable is it? May see if I can get it to build.

Currently it segfaults when stopping or skipping, and pretty much only the timer view works. I'm still working on new timer internals, so that it will be possible to have session indicator and strict mode. The easiest way to try it is by using GNOME Builder, choosing Flatpak as a build method.

**Comment by kamilprusko** [comment]
I've updated it to look more like in gtk4 branch:

Screenshot from 2023-02-05 17-40-23

The stop button gets shown after pausing the timer.

Thank you @jimduchek for contributing :)

**Comment by jimduchek** [comment]
I may have introduced a bug, though it may have already existed and simply being able to hit the timer.skip() all willy-nilly now may have just exposed it.  Unsure as I haven't had a chance to dig into it yet, but after a while _all_ breaks become long breaks.  Gotta go into dconf-viewer and zero the 'score' to reset back to proper behavior.

**Pull request merged**
