### PR TITLE
Add Gnome 41 support

### PR DESCRIPTION
**Pull request by mbooth101**
## Pull request checklist

- [X] Lint and unit tests pass locally with my changes
- [ ] Extended the README / documentation, if necessary

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Shell extension does not load on Gnome 41 (Testing on Fedora 35)

## What is the new behavior?

Shell extension works normally on Gnome 41 (Testing on Fedora 35)

### CODE REVIEW

**Comment by mbooth101** [comment]
BTW I'm carrying this change in the gnome-pomodoro packages for Fedora 35 and newer (Gnome 41). Seems to have no regressions compared to Fedora 34 (Gnome 40)

cf. https://src.fedoraproject.org/rpms/gnome-pomodoro/blob/f35/f/gnome-pomodoro.spec#_51

**Comment by kamilprusko** [comment]
Thank you @mbooth101 :)

I'll try GNOME 41 over the weekend. Will let you know if more changes are needed.

**Comment by kamilprusko** [comment]
Sorry for the delay...

Indeed 41 needed very few changes. I tagged new release [0.20.0](https://github.com/gnome-pomodoro/gnome-pomodoro/releases/tag/0.20.0).

**Comment by mbooth101** [comment]
> Sorry for the delay...
> 
> Indeed 41 needed very few changes. I tagged new release [0.20.0](https://github.com/gnome-pomodoro/gnome-pomodoro/releases/tag/0.20.0).

@kamilprusko Thanks! I submitted an update for Fedora 35 (Gnome 41) and newer: https://bodhi.fedoraproject.org/updates/FEDORA-2021-334ee02b27

**Pull request merged**
